import Foundation

public enum SwiftEmitterError: Error { case invalidIdentifier }

public enum SwiftEmitter {
  public static func emit(manifests: [Manifest]) -> String {
    do { return try emitStrict(manifests: manifests) } catch { return "" }
  }

  public static func emitStrict(manifests: [Manifest]) throws -> String {
    for m in manifests {
      try check(m.host)
      try check(m.pathPrefix)
      try check(m.file)
      try check(m.displayName)
    }
    let body: String
    if manifests.isEmpty {
      body = "      public static let all: [PluginManifest] = []"
    } else {
      let entries = manifests.map { m in
        let resource = m.file.replacingOccurrences(of: ".js", with: "")
        return
          #"        PluginManifest(host: "\#(m.host)", pathPrefix: "\#(m.pathPrefix)", jsResource: "\#(resource)", displayName: "\#(m.displayName)")"#
      }.joined(separator: ",\n")
      body = """
              public static let all: [PluginManifest] = [
        \(entries)
              ]
        """
    }
    return """
      // GENERATED by tools/PluginManifestGen. DO NOT EDIT.
      extension PluginRegistry {
        public enum BundledPlugins {
      \(body)
        }
      }
      """
  }

  private static func check(_ s: String) throws {
    if s.contains(#"""#) || s.contains("\\") { throw SwiftEmitterError.invalidIdentifier }
  }
}
