import Foundation

public enum SwiftEmitterError: Error { case invalidIdentifier }

public enum SwiftEmitter {
  public static func emit(manifests: [Manifest]) -> String {
    do { return try emitStrict(manifests: manifests) } catch { return "" }
  }

  public static func emitStrict(manifests: [Manifest]) throws -> String {
    for m in manifests {
      try check(m.host)
      try check(m.pathPrefix)
      try check(m.file)
      try check(m.displayName)
      if let hint = m.emptyHint { try check(hint) }
    }
    let body: String
    if manifests.isEmpty {
      body = "    public static let all: [PluginManifest] = []"
    } else {
      // swift-format adds a trailing comma to the last array element when
      // there are 2+ elements (`multiElementCollectionTrailingCommas: true`)
      // and strips it for a single-element array. Emit each entry without
      // a trailing comma, then re-append one to every entry except the last
      // when there are 2+ entries — matches swift-format's idempotent shape.
      // Emit each PluginManifest argument on its own line — keeps the
      // generated output stable under swift-format (which wraps any
      // PluginManifest line longer than `lineLength: 100` and would
      // otherwise differ between `just generate` (no formatting) and
      // `just format` (formatting). CI runs generate then format-check
      // back-to-back, so the emitted file must already be format-clean.
      let raw = manifests.map { m in
        let resource = m.file.replacingOccurrences(of: ".js", with: "")
        let hint = m.emptyHint.map { "\"\($0)\"" } ?? "nil"
        return """
                PluginManifest(
                  host: "\(m.host)",
                  pathPrefix: "\(m.pathPrefix)",
                  jsResource: "\(resource)",
                  displayName: "\(m.displayName)",
                  emptyHint: \(hint))
          """
      }
      let entries: String
      if raw.count == 1 {
        entries = raw[0]
      } else {
        entries = raw.map { "\($0)," }.joined(separator: "\n")
      }
      body = """
            public static let all: [PluginManifest] = [
        \(entries)
            ]
        """
    }
    // We emit each PluginManifest argument on its own line above, which
    // is the layout swift-format converges on AND the layout SwiftLint's
    // `multiline_arguments` rule treats as correct. No suppression
    // needed; a `// swiftlint:disable multiline_arguments` here would
    // fail `superfluous_disable_command`.
    return """
      // GENERATED by tools/PluginManifestGen. DO NOT EDIT.
      extension PluginRegistry {
        public enum BundledPlugins {
      \(body)
        }
      }

      """
  }

  private static func check(_ s: String) throws {
    if s.contains(#"""#) || s.contains("\\") { throw SwiftEmitterError.invalidIdentifier }
  }
}
