import Foundation

public enum SwiftEmitterError: Error { case invalidIdentifier }

public enum SwiftEmitter {
  public static func emit(manifests: [Manifest]) -> String {
    do { return try emitStrict(manifests: manifests) } catch { return "" }
  }

  public static func emitStrict(manifests: [Manifest]) throws -> String {
    for m in manifests {
      try check(m.host)
      try check(m.pathPrefix)
      try check(m.file)
      try check(m.displayName)
    }
    let body: String
    if manifests.isEmpty {
      body = "    public static let all: [PluginManifest] = []"
    } else {
      // swift-format adds a trailing comma to the last array element when
      // there are 2+ elements (`multiElementCollectionTrailingCommas: true`)
      // and strips it for a single-element array. Emit each entry without
      // a trailing comma, then re-append one to every entry except the last
      // when there are 2+ entries — matches swift-format's idempotent shape.
      let raw = manifests.map { m in
        let resource = m.file.replacingOccurrences(of: ".js", with: "")
        return """
                PluginManifest(
                  host: "\(m.host)", pathPrefix: "\(m.pathPrefix)", jsResource: "\(resource)",
                  displayName: "\(m.displayName)")
          """
      }
      let entries: String
      if raw.count == 1 {
        entries = raw[0]
      } else {
        entries = raw.map { "\($0)," }.joined(separator: "\n")
      }
      body = """
            public static let all: [PluginManifest] = [
        \(entries)
            ]
        """
    }
    // swift-format wraps long PluginManifest(...) calls onto multiple lines
    // (`lineBreakBeforeEachArgument: false`), which `multiline_arguments`
    // flags. swift-format owns layout — disable the rule for this file when
    // there's at least one entry. Empty manifests don't trigger the wrap,
    // and `superfluous_disable_command` would fire if the marker were
    // unconditional.
    let lintDisable = manifests.isEmpty ? "" : "// swiftlint:disable multiline_arguments\n"
    return """
      // GENERATED by tools/PluginManifestGen. DO NOT EDIT.
      \(lintDisable)extension PluginRegistry {
        public enum BundledPlugins {
      \(body)
        }
      }

      """
  }

  private static func check(_ s: String) throws {
    if s.contains(#"""#) || s.contains("\\") { throw SwiftEmitterError.invalidIdentifier }
  }
}
