#!/usr/bin/env bash
#
# Regenerates the bundled canonical token registry used by impersonation
# detection (issue #1102). Pulls authoritative, community-maintained token
# lists, keeps only our supported chains and a curated set of high-value /
# impersonation-prone symbols, and emits a generated Swift source file pinning
# each (chainId, SYMBOL) to its set of legitimate lowercased contract
# addresses.
#
# Why a curated symbol set (not the whole list): treating every ticker in a
# multi-thousand-token list as "protected" would flag every coincidental
# ticker collision as spam. The issue scopes this to popular tokens and
# stablecoins, so we protect a hand-picked set and let the lists supply the
# exact addresses (a wrong canonical address would flag the *real* token as
# spam — so we never hand-type them).
#
# Multiple legitimate deployments per symbol are preserved (native + bridged,
# e.g. USDC vs USDC.e), so "flag outright" never trips a real token.
#
# Usage: scripts/vendor-token-registry.sh
# Requires: curl, jq.
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="Shared/CryptoImport/CanonicalTokenRegistry+Bundled.swift"

# Supported chains (must match ChainConfig).
CHAINS=(1 10 8453 137)

# Curated protected symbols (uppercased). Impersonation-prone stablecoins,
# wrapped assets, blue-chips, and governance tokens. Over-listing is harmless:
# a symbol with no address on a chain is simply not protected there.
PROTECTED=(
  USDC USDT DAI USDC.E DAI.E USDBC FRAX TUSD USDS PYUSD GUSD LUSD
  WETH WBTC CBETH RETH WSTETH STETH
  UNI OP LINK AAVE LDO ENS SNX CRV MKR COMP SUSHI BAL GRT
  MATIC POL ARB
)

# Authoritative multi-chain token lists (Uniswap default + Optimism Superchain).
SOURCES=(
  "https://tokens.uniswap.org"
  "https://static.optimism.io/optimism.tokenlist.json"
)

chains_json=$(printf '%s\n' "${CHAINS[@]}" | jq -R 'tonumber' | jq -s '.')
protected_json=$(printf '%s\n' "${PROTECTED[@]}" | jq -R '.' | jq -s '.')

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

echo "Fetching token lists…" >&2
combined="$tmp/combined.tsv"
: >"$combined"
for url in "${SOURCES[@]}"; do
  echo "  • $url" >&2
  curl -fsS --max-time 60 "$url" \
    | jq -r '.tokens[] | [.chainId, (.symbol | ascii_upcase), (.address | ascii_downcase)] | @tsv' \
      >>"$combined" || {
    echo "ERROR: failed to fetch/parse $url" >&2
    exit 1
  }
done

# Filter to our chains + protected symbols, dedupe, and fold into a nested
# {chainId: {SYMBOL: [addresses]}} object.
nested=$(
  jq -R -s \
    --argjson chains "$chains_json" \
    --argjson protected "$protected_json" '
      ($chains | map({(tostring): true}) | add) as $chainSet
      | ($protected | map({(.): true}) | add) as $symSet
      | [ split("\n")[] | select(length > 0) | split("\t")
          | {chain: .[0], sym: .[1], addr: .[2]}
          | select($chainSet[.chain] and $symSet[.sym]) ]
      | reduce .[] as $r ({};
          .[$r.chain][$r.sym] = ((.[$r.chain][$r.sym] // []) + [$r.addr] | unique))
    ' "$combined"
)

# Coverage report (no silent gaps).
echo "Coverage:" >&2
echo "$nested" | jq -r '
  to_entries[] | "  chain \(.key): " +
  (.value | to_entries | map("\(.key)(\(.value|length))") | join(" "))' >&2
total=$(echo "$nested" | jq '[.. | arrays | length] | add // 0')
echo "  total addresses: $total" >&2

# Emit the generated Swift file.
body=$(
  echo "$nested" | jq -r '
    to_entries | sort_by(.key | tonumber)
    | map(
        "    \(.key): [\n" +
        (.value | to_entries | sort_by(.key)
          | map("      \"\(.key)\": [" +
              (.value | map("\"\(.)\"") | join(", ")) + "]")
          | join(",\n")) +
        "\n    ]"
      )
    | join(",\n")'
)

cat >"$OUT" <<EOF
// Generated by scripts/vendor-token-registry.sh — DO NOT EDIT BY HAND.
// Sources: Uniswap default token list, Optimism Superchain token list.
// Regenerate to refresh: \`scripts/vendor-token-registry.sh\`.
//
// Maps each supported chain id to the curated set of protected token symbols
// (uppercased) and their legitimate lowercased contract addresses. Consumed by
// \`CanonicalTokenRegistry\` for impersonation detection (issue #1102).

extension CanonicalTokenRegistry {
  static let bundled: [Int: [String: [String]]] = [
$body
  ]
}
EOF

echo "Wrote $OUT" >&2
